name: Windows 2022 Phase 1

on:
  workflow_dispatch:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build:
    runs-on: windows-2022

    steps:
      # ۱. دریافت کدهای مخزن اصلی (اختیاری)
      - name: Checkout main repository
        uses: actions/checkout@v4

      # ۲. کلون کردن مخزن paperless-forms با استفاده از توکن
      - name: Clone paperless-forms repository
        uses: actions/checkout@v4
        with:
          repository: Hossein558/paperless-forms
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
          path: paperless-forms # پوشهای که فایلها در آن کلون میشوند

      # ۳. اکسترکت کردن فایل فشرده با پسورد
      - name: Extract archive with password
        run: |
          cd paperless-forms
          
          # توجه: نام "archive.zip" را با نام واقعی فایل فشرده خود جایگزین کنید.
          # سوییچ p- برای پسورد و سوییچ o- برای مسیر استخراج است.
          7z x archive.zip -p"${{ secrets.ZIP_PASSWROD }}" -o"extracted_files"
